/**
 * Product-media coverage and photo work queue (UX fix plan WS-2).
 *
 * Counts every published record by media state, lists wrong-component images
 * the storefront withholds, and orders the records that need exact-model
 * photography by risk: outdoor units, air handlers and matched-system parts
 * first, and records whose model numbers differ from a neighbour's only by
 * capacity, where a shared family photo is most likely to be mistaken.
 *
 * Run: npm run catalog:media   (writes docs/MEDIA-COVERAGE.md)
 */
import { writeFile } from "node:fs/promises";
import review from "../data/catalog/media-review.json";
import { getStorefrontSkus } from "../src/lib/storefront/catalog";
import { componentMismatch, type MediaVerification } from "../src/lib/media-verification";

const OUT = new URL("../docs/MEDIA-COVERAGE.md", import.meta.url);
const STATES: MediaVerification[] = ["verifiedExact", "verifiedFamily", "reference", "missing"];
const RISK: Array<[RegExp, number, string]> = [
  [/outdoor unit|condenser|heat pump/i, 3, "outdoor unit"],
  [/air handler|evaporator coil|furnace/i, 3, "matched-system component"],
  [/indoor unit|cassette/i, 2, "indoor unit"],
];

const skus = getStorefrontSkus();
const counts = Object.fromEntries(STATES.map((state) => [state, 0])) as Record<MediaVerification, number>;
for (const sku of skus) counts[sku.mediaVerification] += 1;

const byCategory = new Map<string, Record<MediaVerification, number>>();
for (const sku of skus) {
  const row = byCategory.get(sku.categoryLabel) ?? (Object.fromEntries(STATES.map((state) => [state, 0])) as Record<MediaVerification, number>);
  row[sku.mediaVerification] += 1;
  byCategory.set(sku.categoryLabel, row);
}

const mismatched = skus.filter((sku) => sku.images.some((image) => componentMismatch(sku.productType, image)));

/** Model stem without the capacity digits: FJ5ANXD36L00 -> FJ5ANXD##L00. */
const stem = (model: string) => model.toUpperCase().replace(/(09|12|18|24|27|30|36|42|48|60)/, "##");
const stems = new Map<string, number>();
for (const sku of skus) if (sku.modelNumber) stems.set(stem(sku.modelNumber), (stems.get(stem(sku.modelNumber)) ?? 0) + 1);

const queue = skus
  .filter((sku) => sku.mediaVerification !== "verifiedExact")
  .map((sku) => {
    const [, weight, role] = RISK.find(([pattern]) => pattern.test(sku.productType)) ?? [null, 1, "accessory or supply"];
    const lookalike = sku.modelNumber ? (stems.get(stem(sku.modelNumber)) ?? 0) > 1 : false;
    const wrong = mismatched.includes(sku) || review.entries.some((entry) => entry.sku === sku.sku && entry.verdict === "withhold");
    return { sku, role, score: weight * 10 + (lookalike ? 5 : 0) + (wrong ? 20 : 0), lookalike, wrong };
  })
  .sort((a, b) => b.score - a.score || a.sku.sku.localeCompare(b.sku.sku));

const label: Record<MediaVerification, string> = {
  verifiedExact: "Exact model",
  verifiedFamily: "Family (labelled)",
  reference: "Unverified reference",
  missing: "No image",
};
const pct = (n: number) => `${Math.round((n / skus.length) * 100)}%`;

const lines = [
  "# Product media coverage",
  "",
  `Generated ${new Date().toISOString().slice(0, 10)} by \`npm run catalog:media\`. ${skus.length} published records.`,
  "Classification: `src/lib/media-verification.ts`. Do not edit this file by hand.",
  "",
  "## By state",
  "",
  "| State | Records | Share |",
  "|---|---:|---:|",
  ...STATES.map((state) => `| ${label[state]} | ${counts[state]} | ${pct(counts[state])} |`),
  "",
  "## By category",
  "",
  `| Category | ${STATES.map((state) => label[state]).join(" | ")} |`,
  `|---|${STATES.map(() => "---:").join("|")}|`,
  ...[...byCategory].sort().map(([category, row]) => `| ${category} | ${STATES.map((state) => row[state]).join(" | ")} |`),
  "",
  "## Wrong-component images (withheld)",
  "",
  "The file name shows a different component than the record. The storefront shows no image for these until a correct photo is mapped in `data/catalog/exact-media.json`.",
  "",
  "| SKU | Model | Type | Withheld file |",
  "|---|---|---|---|",
  ...mismatched.map((sku) => `| ${sku.sku} | ${sku.modelNumber} | ${sku.productType} | \`${sku.images.find((image) => componentMismatch(sku.productType, image))}\` |`),
  "",
  "## Reviewed by eye",
  "",
  `Verdicts from \`data/catalog/media-review.json\` (${review.reviewedAt}). A review can only lower confidence.`,
  "",
  "| SKU | Verdict | Reason |",
  "|---|---|---|",
  ...review.entries.map((entry) => `| ${entry.sku} | ${entry.verdict === "withhold" ? "Withheld" : "Shown as family"} | ${entry.reason} |`),
  "",
  "## Photo work queue",
  "",
  "Every record without exact-model media, highest risk first. *Look-alike* means another record's model number differs only by capacity digits.",
  "",
  "| # | SKU | Model | Type | Current | Why it ranks |",
  "|---:|---|---|---|---|---|",
  ...queue.map(({ sku, role, lookalike, wrong }, index) =>
    `| ${index + 1} | ${sku.sku} | ${sku.modelNumber || "—"} | ${sku.productType} | ${label[sku.mediaVerification]} | ${[wrong && "wrong component", role, lookalike && "look-alike model"].filter(Boolean).join(", ")} |`
  ),
  "",
];

void writeFile(OUT, lines.join("\n")).then(() => {
  console.log(`Exact ${counts.verifiedExact} · family ${counts.verifiedFamily} · reference ${counts.reference} · missing ${counts.missing}`);
  console.log(`Wrong-component images withheld: ${mismatched.length}`);
  console.log(`Wrote ${OUT.pathname}`);
});
